// Notable NBA head coaches — the autocomplete decoy pool for coach-category
// Fan Favorites questions (players/teams already have their own pools). The
// game also unions in each question's own answer names, so this list only
// needs enough breadth to give real decoys, not to be exhaustive.
export const nbaCoaches = [
  "Phil Jackson",
  "Gregg Popovich",
  "Pat Riley",
  "Red Auerbach",
  "Steve Kerr",
  "Erik Spoelstra",
  "Chuck Daly",
  "John Kundla",
  "K.C. Jones",
  "Rudy Tomjanovich",
  "Larry Brown",
  "Rick Carlisle",
  "Doc Rivers",
  "Tom Thibodeau",
  "Mike D'Antoni",
  "Frank Vogel",
  "Nick Nurse",
  "Mike Budenholzer",
  "Tyronn Lue",
  "Michael Malone",
  "Jason Kidd",
  "Steve Nash",
  "Monty Williams",
  "Quin Snyder",
  "Billy Donovan",
  "Dwane Casey",
  "Scott Brooks",
  "George Karl",
  "Jerry Sloan",
  "Don Nelson",
  "Lenny Wilkens",
  "Byron Scott",
  "Mark Jackson",
  "Stan Van Gundy",
  "Jeff Van Gundy",
  "Mike Brown",
  "Nate McMillan",
  "Terry Stotts",
  "Alvin Gentry",
  "Kenny Atkinson",
  "Ime Udoka",
  "Joe Mazzulla",
  "Chris Finch",
  "Taylor Jenkins",
  "JB Bickerstaff",
  "Chauncey Billups",
  "Willie Green",
  "Rick Adelman",
  "Flip Saunders",
  "Mike Fratello",
  "Del Harris",
  "Bill Fitch",
  "Hubie Brown",
  "Tommy Heinsohn",
  "Bill Sharman",
  "Alex Hannum",
  "Dick Motta",
  "Paul Westhead",
  "Larry Bird",
  "Avery Johnson",
  "Vinny Del Negro",
  "Dave Joerger",
  "Fred Hoiberg",
  "Luke Walton",
  "David Blatt",
  "Darvin Ham",
  "Wes Unseld Jr.",
];
