# Generated by Django 5.1.15 on 2026-06-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('logo', models.URLField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Mvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=7, unique=True)),
                ('mvp', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('team_logo_url', models.URLField(blank=True, max_length=300)),
            ],
            options={
                'indexes': [models.Index(fields=['season'], name='trivia_mvp_season_1e5407_idx')],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('person_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('first_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('from_year', models.IntegerField(blank=True, null=True)),
                ('to_year', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='trivia_play_is_acti_d8977f_idx'), models.Index(fields=['last_name'], name='trivia_play_last_na_aa5e19_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayoffSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=7)),
                ('series_id', models.CharField(max_length=20)),
                ('round', models.CharField(max_length=40)),
                ('winner_team_id', models.BigIntegerField()),
                ('winner_name', models.CharField(max_length=100)),
                ('winner_abbreviation', models.CharField(blank=True, max_length=10)),
                ('loser_team_id', models.BigIntegerField()),
                ('loser_name', models.CharField(max_length=100)),
                ('loser_abbreviation', models.CharField(blank=True, max_length=10)),
                ('loser_wins', models.IntegerField()),
                ('total_games', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'playoff series',
                'indexes': [models.Index(fields=['season'], name='trivia_play_season_7184c1_idx')],
                'constraints': [models.UniqueConstraint(fields=('season', 'series_id'), name='uniq_playoff_series')],
            },
        ),
        migrations.CreateModel(
            name='StartingFiveGame',
            fields=[
                ('game_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('game_date', models.CharField(blank=True, max_length=20)),
                ('season', models.CharField(blank=True, max_length=7)),
                ('team_a', models.CharField(max_length=100)),
                ('team_b', models.CharField(max_length=100)),
                ('team_a_logo', models.URLField(blank=True, max_length=300)),
                ('team_b_logo', models.URLField(blank=True, max_length=300)),
                ('final_score', models.CharField(blank=True, max_length=20)),
                ('winning_team', models.CharField(max_length=100)),
                ('starting_5', models.JSONField(default=list)),
            ],
            options={
                'indexes': [models.Index(fields=['season'], name='trivia_star_season_45851a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=20)),
                ('rows', models.IntegerField(default=0)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['dataset', '-created_at'], name='trivia_sync_dataset_faf9b3_idx')],
            },
        ),
    ]
