# Generated by Django 5.1.15 on 2026-06-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playoffseries',
            name='series_id',
            field=models.CharField(max_length=40),
        ),
    ]
