# Generated by Django 5.1.7 on 2026-07-04 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_alter_playoffseries_series_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FanFavoritesQuestion',
            fields=[
                ('qid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('prompt', models.CharField(max_length=200)),
                ('survey_date', models.CharField(blank=True, max_length=10)),
                ('answers', models.JSONField(default=list)),
                ('live', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['live'], name='trivia_fanf_live_48c12f_idx')],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=40)),
                ('mode', models.CharField(default='single', max_length=10)),
                ('score', models.IntegerField(default=0)),
                ('duration_ms', models.BigIntegerField(default=0)),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['game', '-finished_at'], name='trivia_game_game_a28b41_idx')],
            },
        ),
        migrations.CreateModel(
            name='GuessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=40)),
                ('question_id', models.CharField(blank=True, max_length=60)),
                ('answer', models.CharField(max_length=120)),
                ('correct', models.BooleanField(default=False)),
                ('elapsed_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['game', 'question_id'], name='trivia_gues_game_ed4d10_idx'), models.Index(fields=['-created_at'], name='trivia_gues_created_ddfaa2_idx')],
            },
        ),
    ]
