# Generated by Django 5.1.7 on 2026-08-30 10:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0004_fanfavoritesquestion_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('public_id', models.CharField(blank=True, max_length=12)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('message', models.TextField(blank=True)),
                ('page', models.CharField(blank=True, max_length=120)),
                ('game', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('resolved', 'Resolved')], default='new', max_length=10)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'feedback',
                'indexes': [models.Index(fields=['-created_at'], name='trivia_feed_created_823c24_idx'), models.Index(fields=['rating'], name='trivia_feed_rating_bd9a6c_idx'), models.Index(fields=['status'], name='trivia_feed_status_e272c1_idx'), models.Index(fields=['game'], name='trivia_feed_game_9dc1c0_idx')],
            },
        ),
    ]
