# Generated by Django 5.1.7 on 2026-09-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0005_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(db_index=True, max_length=32)),
                ('qid', models.CharField(max_length=48)),
                ('definition', models.JSONField()),
                ('status', models.CharField(default='active', max_length=16)),
                ('quality', models.JSONField(blank=True, default=dict)),
                ('players_referenced', models.JSONField(blank=True, default=list)),
                ('content_hash', models.CharField(max_length=64)),
                ('dataset_version', models.CharField(blank=True, max_length=32)),
                ('created_by', models.CharField(default='generator', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('retired_reason', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['game', 'status'], name='trivia_ques_game_05a4f7_idx')],
                'constraints': [models.UniqueConstraint(fields=('game', 'qid'), name='uniq_question_game_qid'), models.UniqueConstraint(fields=('game', 'content_hash'), name='uniq_question_game_hash')],
            },
        ),
    ]
