/**
 * Picks backend/socket URLs for local development and writes .env.local.
 *
 * Run automatically before `npm run dev` (see package.json "predev"). Each service
 * is resolved independently: if the local port answers we use it, otherwise we fall
 * back to the deployed one. Vite gives .env.local the highest precedence, so no
 * application code participates in this choice.
 *
 * .env.local is generated output: gitignored, rewritten every run, never read back.
 */
import { writeFileSync } from 'node:fs';
import { connect } from 'node:net';
import path from 'node:path';

const REMOTE_BACKEND_URL = 'https://backend-kappa-one-42.vercel.app/api';

// null until a production multiplayer server exists again (see spec §4.2 / §5.5).
// Setting this is the ONLY change needed to enable the socket fallback.
const REMOTE_SOCKET_URL = null;

const LOCAL_BACKEND_URL = 'http://localhost:8000/api';
const LOCAL_SOCKET_URL = 'http://localhost:4000';

/** True if something accepts a TCP connection on the port. 300ms is plenty for loopback. */
function isPortOpen(port, timeout = 300) {
  return new Promise((resolve) => {
    const socket = connect({ host: 'localhost', port });
    const done = (result) => {
      socket.destroy();
      resolve(result);
    };
    socket.setTimeout(timeout);
    socket.once('connect', () => done(true));
    socket.once('timeout', () => done(false));
    socket.once('error', () => done(false));
  });
}

const [backendUp, socketUp] = await Promise.all([isPortOpen(8000), isPortOpen(4000)]);

const lines = [
  '# Generated by scripts/dev-env.mjs on every `npm run dev`. Do not edit or commit.',
];
const report = [];

// --- backend ---
if (backendUp) {
  lines.push(`VITE_BACKEND_URL=${LOCAL_BACKEND_URL}`, 'VITE_ENV_SOURCE_BACKEND=local');
  report.push(`  backend : LOCAL   ${LOCAL_BACKEND_URL}`);
} else {
  lines.push(`VITE_BACKEND_URL=${REMOTE_BACKEND_URL}`, 'VITE_ENV_SOURCE_BACKEND=remote');
  report.push(`  backend : REMOTE  ${REMOTE_BACKEND_URL}   *** PRODUCTION DATA ***`);
}

// --- socket ---
if (socketUp) {
  lines.push(`VITE_SOCKET_URL=${LOCAL_SOCKET_URL}`, 'VITE_ENV_SOURCE_SOCKET=local');
  report.push(`  socket  : LOCAL   ${LOCAL_SOCKET_URL}`);
} else if (REMOTE_SOCKET_URL) {
  lines.push(`VITE_SOCKET_URL=${REMOTE_SOCKET_URL}`, 'VITE_ENV_SOURCE_SOCKET=remote');
  report.push(`  socket  : REMOTE  ${REMOTE_SOCKET_URL}   *** PRODUCTION DATA ***`);
} else {
  // Write no VITE_SOCKET_URL: src/socket.ts already defaults to localhost:4000.
  lines.push('VITE_ENV_SOURCE_SOCKET=unavailable');
  report.push('  socket  : UNAVAILABLE — no local server and none deployed; multiplayer disabled');
}

writeFileSync(path.resolve('.env.local'), lines.join('\n') + '\n');

console.log('\ndev environment');
console.log(report.join('\n'));
if (!backendUp) {
  console.log('\n  Local writes will hit PRODUCTION data. Start the Django backend on :8000 to work locally.');
}
console.log('');
