/**
 * Picks backend/socket URLs for local development and writes .env.local.
 *
 * Run automatically before `npm run dev` (see package.json "predev"). Each service
 * is resolved independently: if the local port answers we use it, otherwise we fall
 * back to the deployed one. Vite merges env files with LATER winning: .env, then
 * .env.local, then .env.${mode}, then .env.${mode}.local — so .env.local only wins
 * because no .env.development file exists today. If one is ever added, it will
 * silently outrank this script's .env.local and the fallback stops working with no
 * error anywhere. An inline `VITE_*=... npm run dev` env var outranks every file.
 *
 * .env.local is generated output: gitignored, rewritten every run, never read back.
 *
 * Set NBA_DEV_ENV_SKIP to skip this probe entirely (e.g. inside a pipeline worktree,
 * which must never touch the user's local ports — see .claude/agents/browser-qa.md).
 */
import { writeFileSync } from 'node:fs';
import { connect } from 'node:net';
import path from 'node:path';

if (process.env.NBA_DEV_ENV_SKIP) {
  console.log('\ndev environment: skipped (NBA_DEV_ENV_SKIP is set) — .env.local left untouched\n');
  process.exit(0);
}

const REMOTE_BACKEND_URL = 'https://backend-kappa-one-42.vercel.app/api';

// null until a production multiplayer server exists again (see spec §4.2 / §5.5).
// Setting this is the ONLY change needed to enable the socket fallback.
const REMOTE_SOCKET_URL = null;

const LOCAL_BACKEND_URL = 'http://localhost:8000/api';
const LOCAL_SOCKET_URL = 'http://localhost:4000';

/** True if something accepts a TCP connection on the port. 300ms is plenty for loopback. */
function isPortOpen(port, timeout = 300) {
  return new Promise((resolve) => {
    const socket = connect({ host: 'localhost', port });
    const done = (result) => {
      socket.destroy();
      resolve(result);
    };
    socket.setTimeout(timeout);
    socket.once('connect', () => done(true));
    socket.once('timeout', () => done(false));
    socket.once('error', () => done(false));
  });
}

// An explicitly-set VITE_BACKEND_URL (e.g. `.claude/skills/qa-protocol/SKILL.md`'s
// `VITE_BACKEND_URL=http://localhost:8100 npm run dev`) already outranks anything this
// script writes, so probing :8000 or writing a VITE_BACKEND_URL line would be misleading
// noise — or worse, inside a pipeline worktree, would reach into the user's own :8000
// (see .claude/agents/browser-qa.md: those ports must never be touched from a worktree).
const backendUrlPinned = Boolean(process.env.VITE_BACKEND_URL);

const [backendUp, socketUp] = await Promise.all([
  backendUrlPinned ? Promise.resolve(false) : isPortOpen(8000),
  isPortOpen(4000),
]);

const lines = [
  '# Generated by scripts/dev-env.mjs on every `npm run dev`. Do not edit or commit.',
];
const report = [];

// --- backend ---
if (backendUrlPinned) {
  report.push(`  backend : EXPLICIT ${process.env.VITE_BACKEND_URL}   (VITE_BACKEND_URL set — probe skipped, nothing written)`);
} else if (backendUp) {
  lines.push(`VITE_BACKEND_URL=${LOCAL_BACKEND_URL}`, 'VITE_ENV_SOURCE_BACKEND=local');
  report.push(`  backend : LOCAL   ${LOCAL_BACKEND_URL}`);
} else {
  lines.push(`VITE_BACKEND_URL=${REMOTE_BACKEND_URL}`, 'VITE_ENV_SOURCE_BACKEND=remote');
  report.push(`  backend : REMOTE  ${REMOTE_BACKEND_URL}   *** PRODUCTION DATA ***`);
}

// --- socket ---
if (socketUp) {
  lines.push(`VITE_SOCKET_URL=${LOCAL_SOCKET_URL}`, 'VITE_ENV_SOURCE_SOCKET=local');
  report.push(`  socket  : LOCAL   ${LOCAL_SOCKET_URL}`);
} else if (REMOTE_SOCKET_URL) {
  lines.push(`VITE_SOCKET_URL=${REMOTE_SOCKET_URL}`, 'VITE_ENV_SOURCE_SOCKET=remote');
  report.push(`  socket  : REMOTE  ${REMOTE_SOCKET_URL}   *** PRODUCTION DATA ***`);
} else {
  // Write no VITE_SOCKET_URL: src/socket.ts already defaults to localhost:4000.
  lines.push('VITE_ENV_SOURCE_SOCKET=unavailable');
  report.push('  socket  : UNAVAILABLE — no local server and none deployed; multiplayer disabled');
}

try {
  writeFileSync(path.resolve('.env.local'), lines.join('\n') + '\n');
} catch (err) {
  console.warn(`\n  Warning: could not write .env.local (${err.message}). Continuing without it — npm run dev will use whatever .env provides.\n`);
  process.exit(0);
}

console.log('\ndev environment');
console.log(report.join('\n'));
if (!backendUrlPinned && !backendUp) {
  console.log('\n  Local writes will hit PRODUCTION data. Start the Django backend on :8000 to work locally.');
}
console.log('');
