# Generated by Django 5.1.7 on 2025-09-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(choices=[('Rookie', 'Rookie'), ('Role Player', 'Role Player'), ('Sixth Man', 'Sixth Man'), ('Starter', 'Starter'), ('All-Star', 'All-Star'), ('All-NBA', 'All-NBA'), ('MVP', 'MVP'), ('Hall of Famer', 'Hall of Famer'), ('GOAT', 'GOAT')], default='Rookie', max_length=20),
        ),
    ]
