# Generated by Django 5.1.15 on 2026-09-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_blockeduser_friendrequest_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
