# Generated by Django 5.1.15 on 2026-10-01 08:07
"""Drop six single-column indexes that duplicated the ForeignKey indexes.

Supabase's performance advisor (2026-10-01) flagged each Meta.indexes entry on
FriendRequest (receiver, sender), Friendship (user_low, user_high) and
BlockedUser (blocker, blocked) as identical to the index Django already creates
for the ForeignKey column (e.g. users_friendrequest_receiver_id_f5e8f233).
Only the Meta.indexes copies are removed; the FK indexes and the composite
uniq_* constraints stay, so the friends/blocking lookups remain indexed.
Reversing this migration recreates the dropped indexes.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customuser_profile_photo_version"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="blockeduser",
            name="users_block_blocker_94f572_idx",
        ),
        migrations.RemoveIndex(
            model_name="blockeduser",
            name="users_block_blocked_436614_idx",
        ),
        migrations.RemoveIndex(
            model_name="friendrequest",
            name="users_frien_receive_b1f804_idx",
        ),
        migrations.RemoveIndex(
            model_name="friendrequest",
            name="users_frien_sender__a701dd_idx",
        ),
        migrations.RemoveIndex(
            model_name="friendship",
            name="users_frien_user_lo_632d1b_idx",
        ),
        migrations.RemoveIndex(
            model_name="friendship",
            name="users_frien_user_hi_f8de02_idx",
        ),
    ]
