# Generated by Django 5.1.15 on 2026-10-06 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_duplicate_fk_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="ban_reason",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="customuser",
            name="banned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="canonical_email",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="strike_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ModerationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_id", models.CharField(blank=True, max_length=12)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("name_signup", "Name at signup"),
                            ("name_change", "Name change"),
                            ("photo", "Profile photo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("severe", "Severe"),
                            ("mild", "Mild"),
                            ("reserved", "Reserved"),
                            ("none", "None"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(max_length=40)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="modevent_user_created_idx"
                    )
                ],
            },
        ),
    ]
